# Sets and their methods

sampleSet = {1, 2, 3, 4, 5}
sampleSet.add(6)
print(max(sampleSet))
sampleSet.remove(3)
print(sampleSet)
sampleSet.discard(5)
print(sampleSet)
sampleSet.pop()
print(sampleSet)
sampleSet.update((7, 8, 9))
print(sampleSet)
sampleSet2 = sampleSet.copy()
sampleSet2.add(10)
print(sampleSet2)
print(sampleSet2.__contains__(8))
print('union of sampleSet and sampleSet2:', sampleSet.union(sampleSet2))
print('intersection of sampleSet and sampleSet2:', sampleSet.intersection(sampleSet2))
print('difference of sampleSet and sampleSet2:', sampleSet2.difference(sampleSet))
print('is sampleSet2 a subset of sampleSet:', sampleSet2.issubset(sampleSet))
print('is sampleSet2 a superset of sampleSet:', sampleSet2.issuperset(sampleSet))
print('is sampleSet2 disjoint with sampleSet:', sampleSet.isdisjoint(sampleSet2))
sampleSet.update(sampleSet2)
print(sampleSet)
sampleSet2.clear()
sampleSet.clear()
print(sampleSet)

# Dunder methods for sets
my_set = {1, 2, 3}
print(len(my_set))
print(my_set.__len__())
print(2 in my_set)
print(my_set.__contains__(2))
other_set = {2, 3, 4}
print(my_set & other_set)
print(my_set.__and__(other_set))
print(my_set | other_set)
print(my_set.__or__(other_set))
print(my_set - other_set)
print(my_set.__sub__(other_set))
print(my_set ^ other_set)
print(my_set.__xor__(other_set))